# -*- coding: utf-8 -*-
"""Project EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r9niwfe8_MSDNwZL9f3hafSyAz_sG5Q1

# ** EDA on Titanic Dataset**                                        
 Step 1: Import Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style='whitegrid')

"""Step 2: Load the Dataset"""

df = pd.read_csv("train.csv")

""" Step 3: Basic Overview"""

df.head()       # View first 5 rows
df.shape        # Rows and columns
df.columns      # Column names
df.info()       # Data types and non-null counts
df.describe()   # Statistical summary

""" Step 4: Data Cleaning"""

df.isnull().sum()

# Fill missing 'Age' with median
df['Age'].fillna(df['Age'].median(), inplace=True)

# Fill missing 'Embarked' with mode
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

# Drop 'Cabin' (too many missing values)
df.drop(columns=['Cabin'], inplace=True)

"""Step 5: Univariate Analysis
1. Target variable – Survived
"""

sns.countplot(x='Survived', data=df)
plt.title("Survival Count")
plt.show()

"""2. Gender distribution"""

sns.countplot(x='Sex', data=df)
plt.title("Gender Distribution")
plt.show()

"""3. Age distribution"""

sns.histplot(df['Age'], bins=10, kde=True)
plt.title("Age Distribution")
plt.show()

"""Step 6: Bivariate Analysis                                                                                                                                                                                                                                                                                                                          1. Survival vs Gender
python
Copy
Edit
                          
"""

sns.countplot(x='Sex', hue='Survived', data=df)
plt.title("Survival by Gender")
plt.show()

"""2. Survival vs Passenger Class"""

sns.countplot(x='Pclass', hue='Survived', data=df)
plt.title("Survival by Passenger Class")
plt.show()

"""3. Survival vs Embarked"""

sns.countplot(x='Embarked', hue='Survived', data=df)
plt.title("Survival by Embarked Port")
plt.show()

"""4. Age vs Survival"""

sns.boxplot(x='Survived', y='Age', data=df)
plt.title("Age Distribution by Survival")
plt.show()

"""Step 7: Correlation Heatmap"""

corr = df.corr(numeric_only=True)
plt.figure(figsize=(8,6))
sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()